# Generated by Django 4.2.8 on 2023-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id_bus', models.IntegerField(db_column='ID_Bus', primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company_Name', max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Abbreviation', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=100, null=True)),
                ('employee_acc', models.SmallIntegerField(blank=True, db_column='Employee_acc', null=True)),
                ('number_registration', models.IntegerField(blank=True, db_column='Number_registration', null=True)),
                ('name_authorized', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name_authorized', max_length=50, null=True)),
                ('position', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Position', max_length=50, null=True)),
                ('phone_comp', models.IntegerField(blank=True, db_column='Phone_comp', null=True)),
                ('email_comp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email_comp', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Business_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id_child', models.SmallIntegerField(db_column='ID_Child', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Category_child',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id_parent', models.SmallIntegerField(db_column='ID_Parent', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Category_parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id_personal', models.IntegerField(db_column='ID_Personal', primary_key=True, serialize=False)),
                ('picture', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Picture', max_length=300, null=True)),
                ('fullname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fullname', max_length=50, null=True)),
                ('per_taxcode', models.IntegerField(blank=True, db_column='Per_taxcode', null=True)),
                ('phone', models.IntegerField(blank=True, db_column='Phone', null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
                ('name_buyer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name_buyer', max_length=50, null=True)),
                ('mail_invoice', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mail_invoice', max_length=100, null=True)),
                ('name_company', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name_company', max_length=100, null=True)),
                ('comp_taxcode', models.IntegerField(blank=True, db_column='Comp_taxcode', null=True)),
                ('adress_comp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Adress_comp', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Personal_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.IntegerField(db_column='ID_Post', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Title', max_length=300, null=True)),
                ('body', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Body', max_length=600, null=True)),
                ('picture', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Picture', max_length=300, null=True)),
                ('note_pic', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Note_pic', max_length=200, null=True)),
                ('project_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Project_name', max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=4, max_digits=19, null=True)),
                ('creationtime', models.DateTimeField(blank=True, db_column='CreationTime', null=True)),
                ('publishedtime', models.DateTimeField(blank=True, db_column='PublishedTime', null=True)),
                ('active', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Active', max_length=30, null=True)),
                ('area', models.FloatField(blank=True, db_column='Area', null=True)),
                ('bedroom', models.SmallIntegerField(blank=True, db_column='Bedroom', null=True)),
                ('toilet', models.SmallIntegerField(blank=True, db_column='Toilet', null=True)),
                ('furniture', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Furniture', max_length=50, null=True)),
                ('facade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Facade', max_length=50, null=True)),
                ('house_direction', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='House_Direction', max_length=50, null=True)),
                ('way', models.FloatField(blank=True, db_column='Way', null=True)),
                ('pacony_direction', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pacony_Direction', max_length=50, null=True)),
                ('floor', models.SmallIntegerField(blank=True, db_column='Floor', null=True)),
            ],
            options={
                'db_table': 'Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='ID_Region', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=50, null=True)),
                ('ward', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ward', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50, null=True)),
                ('province', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(db_column='ID_User', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Username', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, db_column='Phone', null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
