# Generated by Django 4.2.8 on 2024-01-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('ten_huyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'huyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('ten_tinh', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tinh',
                'managed': False,
            },
        ),
    ]
