# Generated by Django 4.2.8 on 2024-01-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
